FROM php:8.3-cli-alpine

RUN apk add --no-cache libcurl curl-dev \
    && docker-php-ext-install pdo pdo_mysql curl

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . .

RUN composer install --no-interaction --prefer-dist

CMD ["vendor/bin/phpunit", "--colors=always"]
